# Generated by Django 5.2 on 2025-05-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_customuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
