# Generated by Django 5.2 on 2025-04-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_product_created_at_remove_product_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="total_ratings",
        ),
    ]
