# Generated by Django 5.2 on 2025-06-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_order_address_order_payment_method_order_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
