# Generated by Django 5.2 on 2025-05-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_order_orderitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="ordered_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="total_amount",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="product_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
